HGRESEARCH-28_Add_Snakefile_and_BlackBox
bioinformatics-IBCH/variantics pull request #2
Opened 2019-10-11 10:59 UTC by Welekie

2019-10-14 07:27 UTC, dezzan requested changes

2019-10-14 07:27 UTC, dezzan commented on BlackBox.py
> +x = '/home/Welekie/Cursed'
Для передачи аргументов давай использовать библиотеку `argparse`, пример есть в ```src/fact/cli.py```

Также сам файл должен находиться в src/variantics и давай назовем его variantics.py

Должно получиться что-то вроде 
```
python variantics.py --vcf ... --output ... --type WES
```

Почему именно такое расположение почитай, пожалуйста, в infra-readme в разделе ```Project Structure```.

2019-10-14 07:27 UTC, dezzan commented on BlackBox.py
> +Papka = os.listdir(x)
На входе должен быть либо файл с перечислением всех входных VCF, либо путь до файла. Бегать по папке не придется.

2019-10-14 07:27 UTC, dezzan commented on BlackBox.py
> +	p = i.split('.')
Вообще у строки есть функция endswith, которой можно проверить это. Однако у этого подхода есть недостаток: файл может быть gzip'нут, а не bgzip'нут, что вызовет ошибку. Более эффективный подход в  то, чтобы явно проверить формат файла. Вот пример:
``` python
def _check_gzipped_input(in_file):
    """Determine if a gzipped input file is blocked gzip or standard.
    """
    is_bgzip = subprocess.check_output(["grabix", "check", in_file])
    return is_bgzip.strip() == "yes"
``` 
или на баше:
``` bash
grabix check <filename>
```

Данный шаг не должен быть в коде variantics, а должен быть одним из первый шагов в пайплайне snakemake, он отвечает за весь процессинг, а variantics.py - за подготовку конфигурации процессинга.

2019-10-14 07:27 UTC, dezzan commented on Snakefile
> +		"Vivod.tab.gz"
Выходной файл давай называть variant_statistics.tab.gz

2019-10-14 07:27 UTC, dezzan commented on Snakefile
> +		"/usr/local/bin/bcftools filter --output minDP_10_minGQ_15.vcf -i 'MIN(DP)>10 && MIN(GQ)>15'  {input}"
Если мне не изменяет, мы договорились разобраться с этой строчкой

2019-10-14 07:27 UTC, dezzan commented on BlackBox.py
> +name = y + '/' + 'zapusk.txt'
Для увеличения читаемости кода все константны нужно унести либо в переменные в этом же файле/классе, либо в отдельный файлик с константами. В данном случае предлагаю создать constants.py рядом с variantics.py и оттуда импортировать константы

```
CONFIGURATION_NAME = 'config.yaml'
...
```
А в основном коде их явно импортироваться
```
from constants import CONFIGURATION_NAME
```

2019-10-14 07:29 UTC, dezzan commented
Сделай читабельный commit message, пожалуйста

2019-10-17 08:12 UTC, dezzan commented on BlackBox.py
> +	p = i.split('.')
Взгляни, плз, как в примере выше передается команда в subprocess.check_output. Конкатенировать строчки не нужно

2019-10-17 08:16 UTC, dezzan commented on WriteListVcf.py
> +file = open('zapusk2.txt', 'w')
Договорились сделать единую библиотеку ```lib.py```, в которой будут записаны все необходимые функции, а вызываться они будут через различные команды variantics.py. См доку: https://docs.python.org/2/library/argparse.html#sub-commands

2019-10-17 08:17 UTC, dezzan commented on script1.py
> +zapusk = open(str(snakemake.input))
Лишний файл, нужно удалить

2019-10-17 08:21 UTC, dezzan requested changes

2019-10-17 08:21 UTC, dezzan commented on variantics.py
> +	return parser.parse_args()
```return args```?

2019-10-17 08:21 UTC, dezzan commented on variantics.py
> +		if vcf_first_line[0] == '#':
В этом файле плохо с форматированием, лишние табуляции. С PyCharm'ом самому следить за стилем удобнее - попробуй, пожалуйста

2019-10-17 08:21 UTC, dezzan commented on variantics.py
> +		a = 'cp WriteListVcf.py '+ args.output + '/WriteListVcf.py;' + 'cp Snakefile ' + args.output + '/Snakefile; cd ' + args.output + '; snakemake --use-conda variant_statistics.tab.gz'
Вместо 
```
args.output + '/WriteListVcf.py;'
```
корректнее сделать так:
```
os.path.join(args.output, 'whatever')
```

2019-10-17 08:21 UTC, dezzan commented on variantics.py
> +	if args.type == 'WES':
Добавь, плз,  ```choices``` в argparse (см. доку)

2019-10-17 08:27 UTC, dezzan commented on variantics.py
> +		a = 'cp WriteListVcf.py '+ args.output + '/WriteListVcf.py;' + 'cp Snakefile ' + args.output + '/Snakefile; cd ' + args.output + '; snakemake --use-conda variant_statistics.tab.gz'
Копировать сами питоновский файлики не стоит. У тебя же есть доступ к command-line'у variantics'а?

2019-10-17 08:29 UTC, dezzan commented on variantics.py
> +		a = 'cp WriteListVcf.py '+ args.output + '/WriteListVcf.py;' + 'cp Snakefile ' + args.output + '/Snakefile; cd ' + args.output + '; snakemake --use-conda variant_statistics.tab.gz'
Snake make тоже не запускай из подпапки, пожалуйста. Передай в параметры ```outdir``` и в самих командах пайплайна смотри на {params.outdir} и пиши в подпапку

2019-10-17 13:45 UTC, Welekie reviewed
Произошла ошибка с названием коммита.
В коммите я поменял функцию фильтра на новую

2019-10-22 08:21 UTC, dezzan commented on variantics.py
> +		output = open('Const.txt','w')
А почему ты решил так делать, а не прокидывать дальше args.output как переменную?

2019-10-22 08:22 UTC, dezzan commented on variantics.py
> +		if vcf_first_line[0] == '#':
Еще актуально

2019-10-22 08:22 UTC, dezzan commented on variantics.py
> +	file = open('zapusk2.txt', 'w')
```file``` - специальная переменная, лучше переименовать (к примеру, в ```fl```)

2019-10-22 08:24 UTC, dezzan commented on variantics.py
> +	w = open('variant_statistics.tab.gz','w')
Слабо понимаю назначение этой функции. Было бы здорово писать docstring - описание метода. См. пример в ```src/fact/lib.py```

2019-10-29 23:25 UTC, dezzan commented on script1.py
> +zapusk = open(str(snakemake.input))
Сделай, пожалуйста

2019-10-29 23:26 UTC, dezzan commented on lib.py
> +    a = ' cp ' + args.vcf + ' ' + os.path.join(output_first_line, 'variant_statistics.tab.gz')
Это больше не требуется

2019-10-29 23:26 UTC, dezzan commented on WriteListVcf.py
> +file = open('zapusk2.txt', 'w')
Файл нужно удалить

2019-10-29 23:28 UTC, dezzan commented on Snakefile
> +workdir: config["results_folder"]
Вся магия:
https://snakemake.readthedocs.io/en/stable/snakefiles/configuration.html#configure-working-directory

Это я доку почитал :)

2019-10-29 23:30 UTC, dezzan commented on variantics.py
> +    eval(args.command)(args)
Эта строчка понятна?

2019-10-31 20:07 UTC, dezzan commented on lib.py
> +            print('Не работает!')
Юнит тесты :)

2019-11-11 10:41 UTC, dezzan commented on lib.py
> +            "Age": csv.Age.tolist(),
Напоминаю про отдельный PR

2020-01-22 07:35 UTC, merged