HGRESEARCH-33_Histigram_first_step_try_use_pysam_very_bad_tool_to_vcf
bioinformatics-IBCH/variantics pull request #4
Opened 2019-11-18 10:01 UTC by Welekie

2019-11-18 10:49 UTC, dezzan commented on lib.py
> +        rec.info = rec.info + ';' + str(A)     # костыль, не знаю как нормально добавить гистограмы
```
rec.info['VDDHIST'] = ...
```

Почему str(A)?  PySam не умеет сериализовать?

2019-11-21 10:13 UTC, dezzan commented on Brave/TestMetaData.ipynb
> +{
Удали, пожалуйста, ноутбук

2019-11-29 07:41 UTC, dezzan requested changes

2019-11-29 07:41 UTC, dezzan commented on lib.py
> +from cyvcf2 import VCF, Writer
Этот файлик не нужен ведь?

2019-11-29 07:43 UTC, dezzan commented on src/hist/lib.py
> +from cyvcf2 import VCF, Writer
Этот модуль нужно добавить в requirements

2019-11-29 07:47 UTC, Welekie commented on src/hist/lib.py
> +from cyvcf2 import VCF, Writer
colorama >= 0.4.0
exitstatus == 1.3.0
pandas >= 0.25.1
cyvcf2 >= 0.11.5
вот что у меня в requirements
какой модуль надо еще добавить?

2019-11-29 07:49 UTC, dezzan commented on src/hist/lib.py
> +from cyvcf2 import VCF, Writer
Вот, что у тебя в requirements:
https://github.com/bioinformatics-IBCH/variantics/blob/HGRESEARCH-33_Histigram/requirements.txt

Если там есть локальные изменения, их тоже нужно коммитить

2019-12-16 10:57 UTC, dezzan commented on src/hist/valid.py
> +    if str(type(check[0])) == "<class 'numpy.ndarray'>":
Проверять тип нужно через isinstance

2019-12-16 11:01 UTC, dezzan commented on src/hist/valid.py
> +    check = [1 for i in csv.index]
Не называй разные по смыслу переменные одинаково, плз: check и Check

Желательно, чтобы они несли описание того, что содержат.

2019-12-16 11:01 UTC, dezzan commented on src/hist/valid.py
> +        return False
Это неверное условие. Часть бинов могут быть нулевыми, их не нужно учитывать.

2019-12-16 11:02 UTC, dezzan commented on src/hist/valid.py
> +    check = [1 for i in csv.index]
Имеется в виду  такое?
```
.. = [1] * len(csv) 
```

2019-12-16 11:02 UTC, dezzan commented on src/hist/valid.py
> +def validation(csv):
Напиши, пожалуйста, тесты, как обсуждали в Слаке

2019-12-16 11:03 UTC, dezzan commented on src/hist/lib.py
> +		A[1][j] = A[1][j].tolist()
Зачем это?

2019-12-16 11:04 UTC, dezzan commented on src/hist/lib.py
> +    MidMas = [MasBin[1],MasBin[4]]
MasBin, MidMas - запутать пытаешься?:)

2019-12-16 11:04 UTC, dezzan commented on src/hist/valid.py
> +def proverka(check):
Мне не вполне понятно, что тут происходит. Опиши идею в docstring, пожалуйста

2019-12-16 11:06 UTC, dezzan commented on src/hist/valid.py
> +        b = b * i
Бины - это разве не многомерный массив? Тут ты предполагаешь, что он одномерный и с натуральными числами, но это в общем случае нет так ведь?

2020-01-31 14:27 UTC, closed without merging